ccflags-y :=	-Wall				\
		-Wextra				\
		-Wno-missing-field-initializers	\
		-Wno-unused-parameter		\
		-Wformat			\
		-O2				\
		-std=gnu18			\
		-g				\
		-Werror=format-security		\
		-Werror=implicit-function-declaration

dm_crypt-y := dm-crypt.o

obj-m := dm_crypt.o

